### ISSUE TITLE
Golang Readme shows incorrect environment variable key

### ISSUE THREAD

**Issue by maafk** [cdklabs/publib#430]
The README shows `GITHUB_TOKEN` as a required environment variable for publishing to golang, but the default Secret used in projen is `GO_GITHUB_TOKEN` ([ref](https://github.com/projen/projen/blob/main/src/release/publisher.ts#L909))

**Comment by Chriscbr** [comment]
It's true that projen expects the token to be provided as GO_GITHUB_TOKEN, but GITHUB_TOKEN is still the name expected by publib's API, so I believe the README is correct. See an example usage here: https://github.com/projen/projen/blob/aed5aa208eca585249fdea7540d804306b15813d/.github/workflows/release.yml#L253-L258

**Comment by Chriscbr** [comment]
I'm closing this out for housekeeping sake - but if you find any other issues with the docs feel free to open a new issue.
