### ISSUE TITLE
Publish to NPM fails with PNPM

### ISSUE THREAD

**Issue by AminFazlMondo** [cdklabs/publib#969]
As I upgraded the repository with `PNPM` as package manager, the publish to npm registrery fails with the following message:

```
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access
npm ERR! code E415
npm ERR! 415 Unsupported Media Type - PUT https://registry.npmjs.org/<mypackage> - Hard link is not allowed
```

**Comment by gmeligio** [comment]
I was having the same problem publishing a JSII library and it turned out to be the packaging command instead of the publishing one. I fixed it with:

```bash
jsii-pacmak -v --pack-command 'pnpm pack' --target js
```
